---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - repo: https://github.com/willthames/ansible-lint.git
    rev: v6.10.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        exclude: molecule/
