---
{% raw -%}
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Find gzipped Apt indexes
      find:
        paths: /var/lib/apt/lists
        patterns: '*lz4'
      register: __gzipped_apt_indexes

    - name: Cleanup gzipped Apt indexes
      file:
        state: absent
        path: "{{ item.path }}"
      with_items: "{{ __gzipped_apt_indexes.files }}"

    - name: Disable Apt GzipIndexes (Debian Bug report logs - 617856)
      replace:
        dest: /etc/apt/apt.conf.d/docker-gzip-indexes
        regexp: 'Acquire::GzipIndexes "true"'
        replace: 'Acquire::GzipIndexes "false"'

    - name: Install iproute (Allow Ansible Network facts to be populated)
      apt:
        state: present
        name: iproute
        update_cache: true
  tags: always
{%- endraw %}
